---
sidebar: sidebar 
permalink: task-gcp-enable-data-services.html 
keywords: google buckets, google storage, google cloud storage working environment, google cloud storage buckets 
summary: Depois de descobrir os buckets do Google Cloud Storage no BlueXP , você pode usar os serviços de dados do NetApp para backup, disposição em categorias e sincronização de dados. 
---
= Use os serviços de dados do NetApp com buckets do Google Cloud Storage
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Depois de descobrir os buckets do Google Cloud Storage no BlueXP , você pode usar os serviços de dados do NetApp para backup, disposição em categorias e sincronização de dados.

* Use *backup e recuperação do BlueXP * para fazer backup dos dados dos sistemas ONTAP e Cloud Volumes ONTAP no local para o storage de objetos do Google Cloud.
+
Para começar, vá para o Canvas e arraste e solte um ambiente de trabalho ONTAP ou Cloud Volumes ONTAP no ambiente de trabalho do Google Cloud Storage.

+
https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Saiba mais sobre como fazer backup de dados do ONTAP no Google Cloud Storage"^].

* Use a *disposição em camadas do BlueXP * para categorizar dados inativos de clusters do ONTAP no local para o storage de objetos do Google Cloud.
+
Para começar, vá para o Canvas e arraste e solte um ambiente de trabalho do ONTAP no ambiente de trabalho do Google Cloud Storage.

+
https://docs.netapp.com/us-en/bluexp-tiering/task-tiering-onprem-gcp.html["Saiba mais sobre a disposição em camadas dos dados do ONTAP no Google Cloud Storage"^].

* Use *cópia e sincronização do BlueXP * para sincronizar dados com ou a partir dos buckets do Google Cloud Storage.
+
Para começar, vá para o Canvas e arraste e solte o ambiente de trabalho de origem no ambiente de trabalho de destino. Seu ambiente de trabalho do Google Cloud Storage pode ser a origem ou o destino.

+
Você também pode selecionar seu ambiente de trabalho do Google Cloud Storage e clicar em *Copiar e sincronizar* no painel Serviços para sincronizar dados de ou para buckets do Cloud Storage.

+
https://docs.netapp.com/us-en/bluexp-copy-sync/concept-cloud-sync.html["Saiba mais sobre o serviço de cópia e sincronização do BlueXP"^].


